import { Metadata } from 'next';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import HashtagGeneratorContent from './HashtagGeneratorContent';

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://instapsv.com';

export const metadata: Metadata = {
    alternates: {
        canonical: '/instagram-hashtag-generator',
    },
    title: 'Instagram Hashtag Generator — Free & Trending | InstaPSV',
    description: 'Generate the best trending Instagram hashtags for your niche instantly — 100% free. Boost reach, get more likes, and grow your account faster with our smart hashtag finder.',
    keywords: 'instagram hashtag generator, trending instagram hashtags, hashtag finder free, instagram hashtags for likes, best hashtags for instagram 2025, ig hashtag tool',
    openGraph: {
        title: 'Instagram Hashtag Generator — Free & Trending | InstaPSV',
        description: 'Generate trending Instagram hashtags for your niche. Boost reach & get more likes. 100% free, instant results.',
        url: `${BASE_URL}/instagram-hashtag-generator`,
        type: 'website',
        siteName: 'InstaPSV',
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Instagram Hashtag Generator — Free & Trending | InstaPSV',
        description: 'Generate trending Instagram hashtags for free. Boost reach & get more likes instantly.',
    },
};

const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
        {
            '@type': 'Question',
            name: 'How many hashtags should I use on Instagram?',
            acceptedAnswer: {
                '@type': 'Answer',
                text: 'Instagram allows up to 30 hashtags per post, but research suggests that 5–15 highly relevant hashtags perform best. Using too many generic hashtags can reduce visibility. InstaPSV\'s generator curates targeted lists so you always have the right number of quality hashtags.',
            },
        },
        {
            '@type': 'Question',
            name: 'What are the best hashtags to use on Instagram for more likes?',
            acceptedAnswer: {
                '@type': 'Answer',
                text: 'The best hashtags are a mix of: (1) Niche-specific tags (e.g. #travelstories for travel content). (2) Medium-competition tags (100K–1M posts) where you can realistically rank. (3) Branded or community hashtags specific to your audience. Avoid overused mega-tags like #love or #instagood which have billions of posts and zero visibility benefit.',
            },
        },
        {
            '@type': 'Question',
            name: 'Are the hashtags generated by InstaPSV safe from shadowban?',
            acceptedAnswer: {
                '@type': 'Answer',
                text: 'Yes. InstaPSV only generates hashtags that are within Instagram\'s community guidelines. We avoid banned or flagged hashtags that can trigger a shadowban. Our lists are reviewed regularly to remove any tags that Instagram has restricted.',
            },
        },
        {
            '@type': 'Question',
            name: 'Can I use these hashtags on Instagram Reels?',
            acceptedAnswer: {
                '@type': 'Answer',
                text: 'Yes. The hashtags generated by InstaPSV work equally well on regular Instagram posts, Stories, and Reels. Using relevant hashtags on Reels can significantly boost discoverability in the Instagram Explore tab and Reels feed.',
            },
        },
        {
            '@type': 'Question',
            name: 'How often should I change my Instagram hashtags?',
            acceptedAnswer: {
                '@type': 'Answer',
                text: 'You should vary your hashtags regularly — ideally with every 3–5 posts. Using the exact same set of hashtags repeatedly can cause Instagram\'s algorithm to treat them as spam, reducing your reach. InstaPSV makes it easy to discover fresh, rotating hashtag sets for your niche.',
            },
        },
        {
            '@type': 'Question',
            name: 'Is the Instagram Hashtag Generator completely free?',
            acceptedAnswer: {
                '@type': 'Answer',
                text: 'Yes. InstaPSV\'s Hashtag Generator is 100% free to use. No account, no payment, and no sign-up is required. Select your niche or category and instantly get a curated list of trending hashtags you can copy with one click.',
            },
        },
    ],
};

export default function HashtagGeneratorPage() {
    return (
        <>
            <script type="application/ld+json" suppressHydrationWarning dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
            <HashtagGeneratorContent
                header={<Header alwaysDark />}
                footer={<Footer />}
            />
        </>
    );
}
